name: Test
on:
 push:
  branches: main
jobs: 
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4   # action to pull repo code

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: "3.10"

   - name: Install dependencies
     run: pip install -r requirements.txt

   - name: Run tests
     run: pytest /tests
 deploy:
   runs-on: self-hosted
   needs: test
   steps:
     - name: Deploy
       run: echo "Hello World"
 
