name: Test
on:
 push:
  branches: main
jobs: 
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4   # action to pull repo code

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: "3.10"

   - name: Install dependencies
     run: pip install -r requirements.txt

   - name: Run tests
     run: pytest tests
 build:
   runs-on: ubuntu-latest
   needs: test
   steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        id: vars
        run: echo "VERSION= ${{github.run_number}}" >> $GITHUB_ENV
      - name: Build Image
        run: | 
              docker build -t ghcr.io/${{ github.repository }}:${{ env.VERSION }} .
              docker tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} ghcr.io/${{ github.repository }}:latest
      - name: Push Docker image
        run: |
             docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
             docker push ghcr.io/${{ github.repository }}:latest
        
  
 deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Deploy
       run: echo "Hello World"
 
